[package]
name = "lokamusic"
version = "1.0.5-2"
description = "lokamusic - a music player"
authors = ["Rafli Ramadhan"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lofty = "0.22"
tokio = { version = "1", features = ["rt", "sync", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
md5 = "0.7"
log = "0.4"
walkdir = "2"
base64 = "0.22"
discord-rich-presence = "0.2"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
urlencoding = "2"
